services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.vizro
    ports:
      - "127.0.0.1:8050:80"

  docs:
    build:
      context: .
      dockerfile: Dockerfile.mkdocs
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/docs
