FROM python:3.12-slim
WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
COPY ./dashboard.py /code/dashboard.py
RUN mkdir -p /code/data/hafen-hamburg-de
COPY ./data/hafen-hamburg-de/db.duckdb /code/data/hafen-hamburg-de/db.duckdb
CMD ["python", "dashboard.py"]
